apiVersion: v1
kind: Pod
metadata:
  name: fake-node1
spec:
  containers:
  - image: 192.168.24.1:8787/fake-node
    name: fake-node1
    volumeMounts:
    - mountPath: /etc/hosts_compute
      name: hosts
      readOnly: true
    - mountPath: /etc/neutron/original
      name: neutron
      readOnly: true
    - mountPath: /etc/nova/original
      name: nova
      readOnly: true      
  nodeName: openshift-worker-0
  volumes:
  - name: hosts
    hostPath:
      path: /home/tripleo-admin/compute_node/hosts
  - name: neutron
    hostPath:
      path: /home/tripleo-admin/compute_node/neutron/etc/neutron
  - name: nova
    hostPath:
      path: /home/tripleo-admin/compute_node/nova_libvirt/etc/nova     
